### ISSUE TITLE
Drop `afhsb`

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epidatr#104]
It's no longer in the production database, and is currently being removed from the API https://github.com/cmu-delphi/delphi-epidata/issues/1141.

Here, this means:
- [ ] drop `pvt_afhsb` and `pvt_meta_afhsb`
- [ ] remove these from documentation (should just happen thanks to Roxygen)

let me know if there are others to add (or add them).

**Comment by dshemetov** [comment]
This seems like a pretty clear cut case. 

There may be other endpoints in the intersection of (1) rarely used, (2) data is present, (3) unclear if ever going to be used, gray zone. Perhaps we'll get to it at some point.
