### ISSUE TITLE
website landing page is jank

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epidatr#117]
This needs to be updated: https://cmu-delphi.github.io/epidatr/
- [x] make a unique landing page for the website that is distinct from the github
- [x] documentation link out
- [x] both notes to changelog
- [x] basic usage example
- [x] get started: epidatr is a bit redundant, move the core here and edit the output to include results from a functional api key
- [x] codecov badge?

**Comment by dsweber2** [comment]
`\dontrun` results in examples that look like this
```
if (FALSE) {
fluview_meta() %>% fetch()
}
```
I would consider this rather jank, but if its the only way to get roxygen to not run the code, then that's that. It would generally be good to have example results in the examples though.ff

**Comment by dshemetov** [comment]
I'm thinking we could those examples from the function documentation and replace them with a link to examples [vignette](https://cmu-delphi.github.io/epidatr/articles/epidatr.html#example-queries-for-every-endpoint).
