### ISSUE TITLE
Address build-args typo in ci

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#124]
E.g., [here](https://github.com/cmu-delphi/epidatr/actions/runs/5226403357/jobs/9437033289?pr=123).  "Warning: Unexpected input(s) 'build-args', valid inputs are ['args', 'build_args', 'error-on', 'check-dir', 'working-directory', 'upload-snapshots', 'upload-results']"

**Comment by dshemetov** [comment]
That line should be removed anyhow - it's better to build vignettes in the CI, as it acts as another sanity check on the package.
