### ISSUE TITLE
Consider `fetch`ing by default?

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatr#144]

**Comment by capnrefsmmat** [comment]
Is there any circumstance where you'd want to manipulate the call object? Or do we anticipate people will run `fetch()` every single time?

In principle I think our API queries always return the same response for a given input, so I don't see people calling `fetch()` multiple times on the same call, and that'd be the only other reason I can think of for keeping it separate.

**Comment by dshemetov** [comment]
One thing I liked about the current interface is that it helps debugging - you can always look at the URL and see if it's been mangled in some way.

We also have the `with_base_url()` modifier to adjust the base url of a call (e.g. staging API). So another thing that's aimed at development.

**Comment by dsweber2** [comment]
There's a couple of arguments that can currently get passed to fetch which would need to be integrated into each endpoint, which feels like awkward boilerplate, at least from a package dev perspective. I suppose good use of `...` could cover that.

**Comment by dshemetov** [comment]
After today's discussion, it seems that we're moving forward with this integration.

We should have a design discussion here about how to implement this. I suspect we can find a way to minimize boiler-plate in each endpoint. One of the ideas brought up was to have a default args list function, like `fetch_args_list()`. I would like one of these arguments to be `download = TRUE/FALSE` that could allow developers to print the epidata_call object for debugging. Maybe other arguments.
