### ISSUE TITLE
Endpoints need to check `...` is empty

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epidatr#201]
It's possible to hand non-existent parameters to the endpoints because `...` isn't checked. The following call should throw an error for example, but doesn't:
```
epidatr::pub_covidcast(
            source = "chng",
            signals = "smoothed_adj_outpatient_covid",
            geo_type = "state",
            time_type = "day",
            geo_values = "*",
            time_values = epidatr::epirange(from = "20170101", to = "20240101"),
            issues = "*",
            fetch_params = fetch_params_list(return_empty = TRUE, timeout_seconds = timeout_seconds)
          )
```
since it should be `fetch_args` and `fetch_args_list`

**Comment by dsweber2** [comment]
the function to check this is `rlang::check_dots_empty()`

**Comment by dsweber2** [comment]
That seems like a reasonable idea for consistency's sake. Otoh, we don't have arguments that are usually easily confused for one another though.

**Comment by nmdefries** [comment]
Okay, then let's not add dots everywhere right now.
