### ISSUE TITLE
In (vignettes/epidatr.Rmd) floating nav bar blocks text when user scrolls up 

### ISSUE THREAD

**Issue by tinatownes** [cmu-delphi/epidatr#246]
In (vignettes/epidatr.Rmd) when the user scrolls up the screen, the floating navigation bar (/html/body/nav/div/div) doesn't retract itself and blocks a line of text:
![Screenshot 2024-02-05 130903](https://github.com/cmu-delphi/epidatr/assets/11445176/eabfaddb-c4ac-48c4-ba47-3445518dc743)

**Comment by dshemetov** [comment]
Are you still having this issue with our updated site? I'm looking [here](https://cmu-delphi.github.io/epidatr/articles/epidatr.html) and can't reproduce this in my browser.

**Comment by tinatownes** [comment]
Hi @dshemetov, I can no longer replicate this issue. I'll close this, thanks for checking.
