### ISSUE TITLE
Fix `covidcast_meta` `fetch_tbl` parsing issues 

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#34]
Running
```
ccm = delphi.epidata::covidcast_meta() %>%
   delphi.epidata::fetch_tbl()
```
yields
```
Warning message:
One or more parsing issues, see `problems()` for details 
```
due to non-date `min_time`, `max_time`, and `max_issue` for time type `week` / data source `nchs-mortality`.

<details>
  <summary>Some investigation code:</summary>

```
library(tidyverse)
library(data.table)
library(delphi.epidata)
library(epiprocess)

ccm = delphi.epidata::covidcast_meta() %>%
  delphi.epidata::fetch_tbl()

probs = problems()

probs %>%
  print(n=50L)

ccm %>%
  # row numbers in probs appear to include the colnames row, so adjust for that when slicing
  slice(unique(probs[["row"]]-1L)) %>%
  select(data_source, signal, time_type, min_time, max_time, max_issue) %>%
  print(n=40L)

ccm_old = covidcast::covidcast_meta()

ccm_old %>%
  map(class)

ccm %>%
  slice(probs[["row"]]-1L) %>%
  left_join(ccm_old, by=c("data_source","signal","geo_type","time_type")) %>%
  select(data_source, signal, time_type, max_time.x, max_time.y, max_issue.x, max_issue.y, min_time.x, min_time.y) %>%
  print(n=50L)
```
</details>

**Comment by brookslogan** [comment]
It's not 100% clear what to do here.  `covidcast::covidcast_meta()` decides to "convert" weeks into dates.  This makes sense when trying to describe/analyze all the signals' metadata at once, but if we were to try to work of each individual signal's metadata separately to, say, try to programmatically form an `epi_archive`, we might want a week type instead.

**Comment by brookslogan** [comment]
Implementing an epi-/other week class may not be worth the trouble.  I worked a bit toward that some time ago [here](https://github.com/brookslogan/old-old-tooling-wip).

**Comment by krivard** [comment]
We are ultimately moving Epidata toward universally using datetimes to indicate reference periods, no matter their length (day, week, etc). Not sure when that work will be completed though. Does that help at all?

**Comment by brookslogan** [comment]
I assume that would resolve this problem, but create others.  A weekly-resolution signal with a "`time_value`" that's a Date may give pause at best, and cause mistakes at worst (at least for me).  But maybe some sort of signal or column renaming could solve that.  Modeling code can probably adapt fine.

**Comment by brookslogan** [comment]
Originally I was closing since seems like it will be auto-resolved anyway.  But we may still want to triage this and decide whether to implement a short-term fix.
