### ISSUE TITLE
Update styling commands to work similarly across systems

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#55]
~`styler::style_pkg()` appears to be inconsistent about formatting vignettes.  I've tried on my system with CRAN and GitHub versions of `styler`, and they don't seem to format the vignettes, and CI complains about that.~  [I just needed to start a new session after upgrading `styler`.]

**Comment by brookslogan** [comment]
Might be worth a line in the README explaining this sort of situation; if CI complains about styling it suggests that the dev needs to upgrade to latest CRAN `styler` and `style_pkg()` in a fresh session.

**Comment by brookslogan** [comment]
Also might note that styling should be followed by re`document()`ing, as the styler can change example code, and those changes should be propagated to the Rd files.

**Comment by dshemetov** [comment]
I added a couple CI actions to automatically handle this:
- [document](https://github.com/r-lib/actions/tree/v2/examples#document-package)
- [style](https://github.com/r-lib/actions/tree/v2/examples#style-package)

TODO:
- [ ] find a way to make sure that the styling CI runs first and then run the document CI after
