### ISSUE TITLE
API call returns data frame instead of string

### ISSUE THREAD

**Issue by willtownes** [cmu-delphi/epidatr#58]
Currently calling the fetch_csv function returns a string representation of the CSV, it would make it easier for users if it was automatically parsed into a data frame or some other appropriate data structure.

**Comment by brookslogan** [comment]
This is the purpose of the `fetch_df` and `fetch_tbl` functions.  If we're using `fetch_csv` in any examples and vignettes, we should move to using `fetch_tbl` instead.
