### ISSUE TITLE
consider more performance CSV parsing

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/epidatr#6]
> tibble::as_tibble(data.table::setDF(data.table::fread(csv.result))) is much faster than readr::read_csv(csv.result) .  For one query I tried the savings were 10% of the fetch time.  (Note that fread has different column type inference rules; e.g., giving some type of numeric geo_value results for both of the above, but we probably want character or factor output.)

**Comment by dshemetov** [comment]
Closing until we get reports of parsing being a bottleneck
