### ISSUE TITLE
Typo: `fip_code`; also, make sure it requires text rather than an integer

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#65]
`fip_code` should be `fips_code` [here](https://github.com/cmu-delphi/epidatr/blob/46665591b6f37f1e68067db7837f2ef7467657c7/R/endpoints.R#L132).

Additionally, this should require a string rather than an integer / strings rather than integers.  (FIPS codes should include appropriate zero padding, so they should be strings.)

**Comment by dshemetov** [comment]
Part of #69
