### ISSUE TITLE
`covidcast_epidata` lacks visibility and documentation

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#71]
We should consider linking to `covidcast_epidata` from `covidcast` docs and vice versa.  `covidcast_epidata` documentation should be improved to make it clear how to use it without jumping to examples, inspecting names of the object, etc.

**Comment by dsweber2** [comment]
potentially add gif of this to the readme

**Comment by dshemetov** [comment]
Closed by #135
