### ISSUE TITLE
Update issues&lags exclusivity checks to also consider `as_of`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#92]
I believe `covidcast` no longer supports `as_of` together with `issues` or `lags`.  Other endpoints might still support.  We should update the client-side checks.  I believe it's also in an Issue somewhere to detect this on the server side as well.

**Comment by dshemetov** [comment]
We might not need to do this in the client, since we can forward an informative error from the server once it's implemented.

**Comment by dshemetov** [comment]
Update: looks like the server doesn't do validation either, so we should add some guardrails after all.
https://api.covidcast.cmu.edu/epidata/covidcast/?data_source=jhu-csse&signals=confirmed_incidence_num&time_type=day&geo_type=state&time_values=20210101&geo_values=*&issues=20210101-20210201&lag=5&as_of=20210301

**Comment by brookslogan** [comment]
Doing checks (a) client-side or (b) both client-side and server-side both make sense.  Currently we have bad checks both client-side and server-side, so both would need updated for either of the above two approaches.

**Comment by dshemetov** [comment]
Update: from the discussion in the linked thread above, I'm now leaning away from doing these validation checks.
