### ISSUE TITLE
SSL error syscall on some systems when running example

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#95]
One user reported an error running an example like this:
```{r}
library(epidatr)
library(dplyr)

geos <- c("ca", "fl", "tx", "ny", "nj")
x <- covidcast(
  data_source = "jhu-csse",
  signals = "confirmed_incidence_num",
  time_type = "day",
  geo_type = "state",
  time_values = epirange(20210604, 20211231),
  geo_values = geos) %>%
  fetch_tbl() %>%
  select(geo_value, time_value, cases = value)

y <- covidcast(
  data_source = "jhu-csse",
  signals = "deaths_incidence_num",
  time_type = "day",
  geo_type = "state",
  time_values = epirange(20210604, 20211231),
  geo_values = geos) %>%
  fetch_tbl() %>%
  select(geo_value, time_value, deaths = value)
```
With the following error message:
```
Error in curl::curl_fetch_memory(url, handle = handle): OpenSSL SSL_connect:
  SSL_ERROR_SYSCALL in connection to delphi.cmu.edu:443
```
A quick google turned up [this post](https://stackoverflow.com/questions/48987512/ssl-connect-ssl-error-syscall-in-connection-to-github-com443) which may be related.  This post makes it seem like it's an outdated library issue that's hard to resolve.  We probably need to query some R and OS library versions from them, but I'm not sure which libraries to ask them to check.  [Some are obvious: OS & R version, OS's curl and ssl versions, R's curl, httr versions.  Maybe see if they can reproduce with command-line curl.]

**Comment by brookslogan** [comment]
This might also be a firewall issue, though I would have thought there would be a better error message in that case.

**Comment by dshemetov** [comment]
Huh, so they managed to install epidatr from github (which I imagine uses curl), but delphi.cmu.edu didn't work? Maybe it's something specific about delphi.cmu.edu?

**Comment by brookslogan** [comment]
After further discussion, this seems like it was a firewall-like issue requiring action on the user side.  I'm  not sure if we can improve the error message encountered; I'm going to close this Issue, but hopefully, having it around will help discoverability for users with similar issues.
