### ISSUE TITLE
Make a vignette with every endpoint example query

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatr#96]
It would be nice to have a vignette with all the example queries from the documentation (e.g. [see Examples at the bottom here](https://cmu-delphi.github.io/epidatr/reference/covid_hosp_facility.html)). 

The private endpoints `pvt_*` require a key. Either we don't do those examples or we write those examples into a cell, but comment them out.

**Comment by dsweber2** [comment]
related? https://github.com/cmu-delphi/epidatr/issues/33

**Comment by dshemetov** [comment]
There might be an example in the `fluview` function doc already, as i tried to do in #23

**Comment by dsweber2** [comment]
on the private endpoints, how do you feel about adding a "dummy" key that returns example data stored in the docs, rather than actually making an api call (and throws a warning that its a dummy)?

**Comment by dsweber2** [comment]
Actually, it would be good to have something similar for the public api key if we can't bury that as a github secret or something like that so the vignettes don't have the API warning

**Comment by brookslogan** [comment]
Closed by #113.  Apparently I didn't use the magic GitHub keywords appropriately to auto-close this.

**Comment by dshemetov** [comment]
For some reason the magic github keywords only work in the OP of a PR @brookslogan
