### ISSUE TITLE
covid_hosp_facility_lookup should warn/error for not implemented cases

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epidatr#98]
Unsure if this exists as an issue already, but the call 
```
covid_hosp_facility_lookup(state = "WY", city = "New York") %>% fetch_tbl()
```
silently just returns the state result. As more than one input is invalid, this should probably return an error/warning to that effect.

**Comment by dshemetov** [comment]
Related to the discussion [here](https://github.com/cmu-delphi/delphi-epidata/issues/1159)
